FROM nginx:stable-alpine

ARG GID
ARG UID
ARG USER

ENV GID=${GID}
ENV UID=${UID}
ENV USER=${USER}

# MacOS staff group's gid is 20, so is the dialout group in alpine linux. We're not using it, let's just remove it.
RUN delgroup dialout

RUN addgroup -g ${GID} --system ${USER}
RUN adduser -G ${USER} --system -D -s /bin/sh -u ${UID} ${USER}
RUN sed -i "s/user  nginx/user ${USER}/g" /etc/nginx/nginx.conf

COPY ./nginx.conf  /etc/nginx/conf.d/
