apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: agala-staging
  name: agala-staging
  namespace: default
spec:
  selector:
    matchLabels:
      app: agala-staging
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: agala-staging
    spec:
      containers:
        - command:
            - /bin/bash
            - -c
          args:
            - cp .docker/php/php.ini /usr/local/etc/php/conf.d/local.ini && composer install && php artisan migrate && php artisan db:seed && php-fpm -y /usr/local/etc/php-fpm.conf -R
          env:
            - name: APP_NAME
              value: "AGala Dev"
            - name: APP_ENV
              value: local
            - name: APP_KEY
              value: "base64:Z2Zpd2puNDlybm5heDhyd3h6c25wdjF0bTlmN2ZhbGs="
            - name: APP_DEBUG
              value: "true"
            - name: APP_URL
              value: "http://agala.test"
            - name: LOG_CHANNEL
              value: "stack"
            - name: LOG_DEPRECATIONS_CHANNEL
              value: "null"
            - name: LOG_LEVEL
              value: "debug"
            - name: DB_CONNECTION
              value: "mysql"
            - name: DB_HOST
              value: "143.198.86.80"
            - name: DB_PORT
              value: "3306"
            - name: DB_DATABASE
              value: "agala_staging"
            - name: DB_USERNAME
              value: "smsuserdb"
            - name: DB_PASSWORD
              value: "Sm3send564!!"
            - name: MAIL_MAILER
              value: "smtp"
            - name: MAIL_HOST
              value: "smtp.office365.com"
            - name: MAIL_PORT
              value: "587"
            - name: MAIL_USERNAME
              value: "koneb2013@hotmail.com"
            - name: MAIL_PASSWORD
              value: "qmtqqvnihasqwdfa"
            - name: MAIL_ENCRYPTION
              value: ""
            - name: MAIL_FROM_ADDRESS
              value: "koneb2013@hotmail.com"
            - name: MAIL_FROM_NAME
              value: "AGala Dev"
          image: neiellcare71/composer:latest
          imagePullPolicy: IfNotPresent
          name: agala-staging
          ports:
            - containerPort: 80
              name: agala-staging
              protocol: TCP
          volumeMounts:
            - mountPath: /var/www
              name: app
            - mountPath: /root/.ssh
              name: id-rsa
      hostname: agala-staging
      initContainers:
        - args:
            - find /app -mindepth 1 -delete; git clone -b develop --depth=1 --single-branch
              git@github.com:TFOE-PE-NMR8/aGala.git /app
          command:
            - /bin/sh
            - -c
          image: alpine/git@sha256:8f5659025d83a60e9d140123bb1b27f3c334578aef10d002da4e5848580f1a6c
          imagePullPolicy: IfNotPresent
          name: init
          volumeMounts:
            - mountPath: /app
              name: app
            - mountPath: /root/.ssh
              name: id-rsa
        - args:
            - cd /app && npm install && npm run development
          command:
            - /bin/bash
            - -c
          image: node:latest
          imagePullPolicy: IfNotPresent
          name: npm
          volumeMounts:
            - mountPath: /app
              name: app
      restartPolicy: Always
      volumes:
        - emptyDir: {}
          name: app
        - name: id-rsa
          secret:
            defaultMode: 384
            items:
              - key: id_rsa
                path: id_rsa
              - key: known_hosts
                path: known_hosts
            secretName: neiell-test
---
apiVersion: v1
kind: Service
metadata:
  name: agala-staging
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: agala-staging
  ports:
    - name: agala-staging
      protocol: TCP
      port: 80
      targetPort: 80
