FROM php:8.1.8-fpm

ARG GID
ARG UID
ARG USER

ENV GID=${GID}
ENV UID=${UID}
ENV USER=${USER}

WORKDIR /var/www

# MacOS staff group's gid is 20, so is the dialout group in alpine linux. We're not using it, let's just remove it.
#RUN delgroup dialout

RUN addgroup --gid ${GID} --system ${USER}
RUN adduser --ingroup ${USER} --system --disabled-login --shell /bin/sh --uid ${UID} ${USER}

RUN sed -i "s/user = www-data/user = ${USER}/g" /usr/local/etc/php-fpm.d/www.conf
RUN sed -i "s/group = www-data/group = ${USER}/g" /usr/local/etc/php-fpm.d/www.conf
RUN echo "php_admin_flag[log_errors] = on" >> /usr/local/etc/php-fpm.d/www.conf

# Install system dependencies
RUN apt-get update && apt-get install -y \
    libpng-dev \
    zlib1g-dev \
    libxml2-dev \
    libzip-dev \
    libonig-dev \
    zip \
    git \
    curl \
    unzip \
    wget \
    libxrender1 \
    libxtst6 \
    fontconfig \
    libjpeg62-turbo \
    xfonts-75dpi \
    xfonts-base \
    libmagickwand-dev \
    && pecl install imagick \
    && docker-php-ext-enable imagick \
    && docker-php-ext-configure gd \
    && docker-php-ext-install -j$(nproc) gd \
    && docker-php-ext-install pdo_mysql \
    && docker-php-ext-install mysqli \
    && docker-php-ext-install zip \
    && docker-php-ext-install mbstring \
    && docker-php-source delete \

# Copy config files
COPY ./php.ini /usr/local/etc/php/php.ini

# Clear cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Install PHP extensions
RUN docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd

# Install Postgre PDO
RUN apt-get update && apt-get install -y libpq-dev && docker-php-ext-install pdo pdo_pgsql


CMD ["php-fpm", "-y", "/usr/local/etc/php-fpm.conf", "-R"]
